
def getErrorMessageAndCodeFromConstant(request,errorConstant):
    errorMessageDictionary = {

        "kInvalidCred": {"code":1,"msg":"Invalid user credentials"},
        "kMissingReqFields":{"code":2,"msg":"Required fields are missing"},
        "kUnauthorisedAction": {"code": 103, "msg": "User is not authorised to do this action"},
        "kInvalidRequest": {"code": 3, "msg": "Data submitted is not valid. Please contact the admin."},
        "kUserExistAlready": {"code": 4, "msg": "User exists already with the Same Contact details, please login"},
        "kUserExistSameOrg": {"code": 5, "msg": "Oragnisation with same name and contact details already exist. Please login."},
        "kInvalidOldPass": {"code":6,"msg":"Invalid old password"},
        "kPassShouldNotMatch": {"code":7,"msg":"Old password and New password should not match"},
        "kPasswordValidationFailed": {"code":8,"msg":"New password should have minimum 8 characters, at least one uppercase and lowercase"},
        "kUserDoesNotExist": {"code":9,"msg":"User Does not exist"},
        "kUnknownError": {"code":10,"msg":"Unknown error please contact Admin"},
        "kPartnerDoesNotExist": {"code":11,"msg":"Partner Does not exist"},
        "kCourseDoesNotExist": {"code":13,"msg":"Course Does not exist"},
        "kAcademicYearDoesNotExist": {"code":15,"msg":"Academic Does not exist"},
        "kCenterDoesNotExist": {"code":16,"msg":"Center Does not exist"},
        "kCourseProviderDoesNotExist": {"code":17,"msg":"Course Provider Does not exist"},
        "kUserProfileDoesNotExist":{"code":18,"msg":"User profile Does not exist"},
        "kDigitalSchoolDoesNotExist":{"code":19,"msg":"Digital school Does not exist"},
        "kRoleDoesNotExist":{"code":20,"msg":"Role Does not exist"},
        "kSchoolNameDuplicate": {"code": 12, "msg": "School name already exist"},
        "kFileUploadFailed":{"code":21,"msg":"File upload failed. Please try again"},
        "kInvalidEmailId":{"code": 14, "msg": "Invalid email Id. Please enter valid email."},
        "kFileDoesnotExist":{"code": 22, "msg": "Attached file does not exist."},
        "kOnlyDigitalPartners": {"code": 23, "msg": "Only digital partners allowed this action."},
        "korgInvalidEmail": {"code": 24, "msg": "Organisation email id is invalid"},
        "kInvalidPartner": {"code": 25, "msg": "Invalid partner"},
        "kInvalidSearchKey": {"code": 26, "msg": "Invalid search key"},
        "kReferenceChannelDoesNotExist": {"code": 27, "msg": "Reference Channel Does not exist"},
        "kInvalidParterDSMCon": {"code": 28, "msg": "Partner and school and DSM are not connected."},
        "kInvalidSchoolStatus":{"code": 29, "msg": "School status should be active"},
        "kDigitalSchoolNotActivated": {"code": 28, "msg": "Digital school Does not exist or not activated"},
        "kSessionExpired": {"code": 29, "msg": "Session expired"},
        "kSessionNotAvailable": {"code": 30, "msg": "Session not available"},
        "kInvalidMobileNum": {"code": 31, "msg": "Invalid mobile number"},
        "kOtpExpired": {"code": 32, "msg": "OTP expired"},
        "kInvalidOtp": {"code": 33, "msg": "OTP is Invalid or Expired"},
        "kOtpNotSent": {"code": 34, "msg": "OTP not sent"},
        "kUserGuardian": {"code": 35, "msg": "User should be guardian and active"},
        "kUserID": {"code": 36, "msg": "User ID should be integer"},
        "kUserGuardianStudent": {"code": 37, "msg": "User should be Guardian or Student"},
        "kdigitalSchoolId": {"code": 38, "msg": "Digital school id shoud be integer"},
        "kStudentId": {"code": 39, "msg": "Student id shoud be integer"},
        "kGradeId": {"code": 40, "msg": "Grade should be integer and greater than 0"},
        "kGradeIdGreater": {"code": 41, "msg": "Grade id should be greater that 0"},
        "kDataFormatWrong": {"code": 42, "msg": "Data format is wrong"},
        "kSystemSettings": {"code": 44, "msg": "System settings is defined wrong"},
        "kSelectTime": {"code": 43, "msg": "Select more time to cover subjects"},
        "kConsentMandatory": {"code": 51, "msg": "Guardian consent is required"},
        "kInvalidStudentRelationType":{"code": 52, "msg": "Invalid relationship type"},
        "kInvalidGender": {"code": 53, "msg": "Invalid gender type"},
        "kInvalidLanguage": {"code": 54, "msg": "Invalid Language"},
        "kInvalidOfferings": {"code": 56, "msg": "Invalid Offerings"},
        "kStudentEnrollmentFailed":{"code": 55, "msg": "Student enrollment failed.Please contact admin"},
        "kInvalidUserType": {"code": 57, "msg": "User is not authorised to view the students"},
        "kStudentNotFound":{"code": 56, "msg": "Invalid student"},
        "kStudentEditFailed": {"code": 58, "msg": "Student edit failed"},
        "kSessionNotFound": {"code": 80, "msg": "Session not found"},
        "kInvalidSession": {"code": 59, "msg": "Invalid session"},
        "kInvalidSubtopic":{"code": 61, "msg": "Invalid subtopic"},
        "kInvalidDoubt":{"code": 62, "msg": "Invalid doubt object"},
        "kInvalidStudentGuardRel":{"code": 64, "msg": "Student not related to user"},
        "kInvalidContent": {"code": 65, "msg": "Invalid content"},
        "kInvalidDoubt": {"code": 66, "msg": "Invalid Doubt"},
        "kAttendPrevSession":{"code": 67, "msg": "Please attend previous class to view this class"},
        "kSlotsNotEnough": {"code": 68, "msg": "Slots are not enough, Please choose more"},
        "kSlotsEditFailed": {"code": 69, "msg": "You are editing scheduling before time table generation"},
        "kInvalidState": {"code": 70, "msg": "Invalid State"},
        "kMaxOTPExceed": {"code": 71, "msg": "Maximum number of OTP has been exceeded. Please try after one hour."},
        "kGuardianExist": {"code": 72, "msg": "Guardian Exist already, please login"},
        "kInvalidLocation": {"code": 73, "msg": "Location Details are Invalid"},
        "kAccessDenied": {"code": 74, "msg": "Please login or enroll student to access this "},
        "kTimetableNotFound": {"code": 77, "msg": "Time table not found. "},
        "kParterRegistrationFailed": {"code": 75, "msg": "Partner registration Failed"},
        "kOrganisationExist": {"code": 76, "msg": "Organization already exist with same details.Please use different name"},
        "kEmailExist":{"code": 78, "msg": "Email already registered with us. Please login or use different email id."},
        "kMobileExist": {"code": 79, "msg": "Mobile already registered with us. Please login or use a different mobile number."},
        "kOrgNameExist": {"code": 80,"msg": "Organisation with this name is already registered with us. Please login or use different organisation."},
        "kDeviceDoesNotExist": {"code": 81,"msg": "Device is not found."},
        "kGradeCannotChange": {"code": 82, "msg": "You cannot change the grade as Time table has been generated.Please contact admin."},
        "kInvalidStudentList": {"code": 83,"msg": "Invalid students list for promotion."},
        "kStudentPromotionFailed": {"code": 84, "msg": "Student promotion failed."},
        "kInvalidPromotionType": {"code": 85, "msg": "Invalid promotion type."},
    }

    if "kCustomErrorMsg" in  errorConstant:
        errorObj = {"code": 101, "msg": errorConstant}
    else:
        errorObj =  errorMessageDictionary.get(errorConstant)
    errorCode,errorMsg = 101, "Invalid data, Please try again!"
    if errorObj is None:
        errorObj = {"code":errorCode,"msg":errorMsg}
    return errorObj