from django.conf.urls import patterns
from django.conf.urls import url
from .views import *
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^signup', SignupView, name='signup'),
    url(r'^profile', profile, name='profile'),
    url(r'^save_profile', save_profile, name='save_profile'),
    url(r'^get_partners_details', get_partners_details, name='get_partners_details'),
    url(r'^deliverypartner_org', deliverypartner_org, name='deliverypartner_org'),
    url(r'^organization_details', organization_details, name='organization_details'),
    url(r'^volunteer_dash', volunteer_dash, name='volunteer_dash'),
    #url(r'^add_schools/?$', add_schools, name='add_schools'),
    url(r'^my_schools', my_schools, name='my_schools'),
    url(r'^get_school_details', get_school_details, name='get_school_details'),
    url(r'^contributions', contributions, name='contribution'),
    url(r'^get_offering_details', get_offering_details, name='get_offering_details'),

    # url(r'^search_school/?$', get_partner_school, name='search_school'), # Added in Main url file as school/search/
    url(r'^save_school/?$', save_partner_school, name='save_school'),
    url(r'^myschool/(?P<myschool_id>\d+)?/?$', view_partner_myschool, name='view_myschool'),
    url(r'^myschool_verification/(?P<myschool_id>\d+)/(?P<verification_type>\w+)?/?$', verify_myschool, name='verify_myschool'),
    url(r'^myschools/?$', list_partner_myschools, name='list_partner_myschools'),
    url(r'^update_myschool_status/(?P<myschool_id>\d+)/?$', update_myschool_status, name='update_myschool_status'),
    url(r'^view_myschool_verify_log/(?P<myschool_id>\d+)/?$', view_myschool_verification_log, name='view_verify_myschool_log'),

    ###################### Become partner ####################
    url(r'^become_partner/?$', TemplateView.as_view(template_name='become_partner.html'), name='profile'),
    url(r'^new_signup/?$', partner_signup),
    url(r'^partners/(?P<partner_id>\d+)?/?$', list_partners),
    url(r'^partners/save_type_status/(?P<partner_id>\d+)?/?$', partner_update_type_status),
    url(r'^centers/?$', list_centers),
    url(r'^(?P<myschool_id>\d+)/addcenter/?$', add_center_to_school),
    url(r'^updateCenter/(?P<center_id>\d+)/(?P<myschool_id>\d+)/?$', update_center),
    url(r'^partner_adminpage/?$', partner_admin_defaultpage),
    url(r'^partner_mou/(?P<partner_id>\d+)?/?$',mou_list),
    url(r'^mou_form/?$',mou_form),
    url(r'^saving_mou/?$',create_mou),
    url(r'^update_mou/(?P<mou_id>\d+)/?$',update_mou),
    url(r'^generate_certificate_for_Memorandum_of_Understanding/(?P<id>\d+)/?$',generate_certificate_for_Memorandum_of_Understanding),
    url(r'^generate_certificate_for_Terms_of_Engagement/(?P<id>\d+)/?$',generate_certificate_for_Terms_of_Engagement),
    url(r'^view_of_mou/(?P<id>\d+)/?$',view_of_mou),
    url(r'^view_of_partner_engagement/(?P<id>\d+)/?$',view_of_partner_engagementt),
    url(r'^ajax/get_my_users/?$', partner_users),
    url(r'^ajax/get_my_select_users/?$', get_my_select_users),
    url(r'^user_save_roles/?$', partner_assign_user_roles),
	url(r'^my_users/?$',my_users),
	url(r'^org_details/?$',org_details),
    url(r'^ajax/get_mou_partner/?$',get_mou_partner),
    url(r'^api/v1/register?$',partner_registration_api),
    url(r'^api/v1/login?$',partner_login_api),
    url(r'^api/v1/school?$', school_api_generic),
    url(r'^api/v1/school/(?P<schoolId>\d+)/?$', update_school_api),
    url(r'^api/v1/documents?$', upload_user_document),
    url(r'^api/v1/users?$', partner_users_api),
    url(r'^api/v1/users/(?P<userId>\d+)/?$', edit_users_api),
    url(r'^api/v1/student/enroll/?$', dsm_enroll_student),
    url(r'^api/v1/languages?$', partner_language_api),
    url(r'^api/v1/students?$', partner_students_list_api),
    url(r'^api/v1/student/(?P<studentId>\d+)/?$', partner_students_detail_api),

    url(r'^api/v1/reset_password?$',reset_password_api),
    url(r'^api/v1/profile/(?P<userId>\d+)/?$',profile_api_generic),
    url(r'^api/v1/courseprovider?$',course_provider_api),
    url(r'^api/v1/course?$',course_api),
    url(r'^api/v1/offering?$',offering_api_generic),
    url(r'^api/v1/academic?$',academic_api),
    url(r'^api/v1/users/assignrole?$',assign_user_school_api),
    url(r'^digitalschools/?$', partner_digitalschools_list_approval, name='list_partner_dsschools'),
    url(r'^digitalschool/(?P<schoolId>\d+)/?$', partner_digitalschools_detail_approval, name='view_digitalschool_su'),
    url(r'^digitalschool/approve/(?P<schoolId>\d+)/?$', digitalschools_approve_su_action, name='approve_digitalschool_su'),
    url(r'^digitalschool/deactivate/(?P<schoolId>\d+)/?$', digitalschools_deactivate_su_action, name='deactivate_digitalschool_su'),
    url(r'^digitalschool/activate/(?P<schoolId>\d+)/?$', digitalschools_activate_su_action, name='activate_digitalschool_su'),
    url(r'^api/v1/states?$',states_api,name='states_api'),
    url(r'^api/v1/ping?$',ping_api,name='ping_api'),
    url(r'^api/v1/logout?$',logout_api,name='logout_api'),
    url(r'^api/v1/pincodes?$', pincodes_api,name='pincodes_api'),
    url(r'^api/v1/schoollocation/add?$', schoollocation_add_api,name='schoollocation_add_api'),
    url(r'^api/v1/schoollocation/delete?$', schoollocation_delete_api,name='schoollocation_delete_api'),
    url(r'^api/v1/explore/schools/detail?$', partner_explore_School_detail,name='partner_explore_School_detail'),
    url(r'^api/v1/subject/detail?$', partner_subject_detail,name='partner_subject_detail'),
    url(r'^api/v1/content/detail?$', partner_content_detail, name='partner_content_detail'),
    url(r'^api/v1/b2c/send_otp?$', partner_send_otp_api, name='partner_send_otp_api'),
    url(r'^api/v1/b2c/register?$', partner_verify_otp_registration_api, name='partner_verify_otp_registration_api'),
    url(r'^api/v1/b2c/update_details?$', partner_details_update_api, name='partner_details_update_api'),
    url(r'^api/v1/grades?$', partner_get_grade, name='partner_get_grade'),
    url(r'^api/v1/checkcourse?$', partner_check_offering_exist_forcourse, name='partner_check_offering_exist_forcourse'),
    url(r'^api/v1/updatetoken?$', partner_update_token_api, name='partner_update_token_api'),
    url(r'^api/v1/students/promotion', dsm_promot_student,name="partner_students_grade_promotion"),
    url(r'^api/v1/students/promotelist', dsm_promot_student_list,name="partner_students_promotion_list"),
    url(r'^quizplayer/?$', QuizPlayer.as_view(), name='quizplayer'),
    url(r'^quiz/submit_answer/$', SubmitAnswer.as_view(), name= 'submit_answer'),
    url(r'^digitalschool/update/(?P<schoolId>\d+)/?$', updateDigitalSchool, name='update_digitalschool'),
    ]
