from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from registration.views import register
from registration.forms import RegistrationFormUniqueEmail
from django.views.generic import RedirectView
from partner.views import get_partner_school
from django.views.generic import TemplateView
from web.sitemaps import websitemap
from django.contrib.sitemaps.views import sitemap
from django.http import HttpResponse
sitemaps = {
    'websitemap': websitemap,
}


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'

urlpatterns = patterns('web.views',
    #url(r'^grappelli/', include('grappelli.urls')),
    # Examples:
    #url(r'^$', 'home', name='home'),
    # url(r'^facebook/?', include('django_facebook.urls')),
    #url(r'^facebook/connect/?$', 'user_profile', name='home'),
    # url(r'^submit/?$', 'user_profile'),
    url(r'save_user_profile/?$', 'save_profile'),
    url(r'save_center_timings/?$', 'save_center_timings'),
    url(r'save_students/?', 'save_students'),
    url(r'save_offering/?$', 'save_offering'),
    url(r'save_remarks/?$', 'save_remarks'),
    url(r'^get_user_emails/?', 'get_user_emails'),
    url(r'^send_mail/?$', 'send_email'),
    url(r'^download/?$', 'download'),
    url(r'assign_center/?$', 'assign_center'),
    url(r'^response/?$', 'response'),
    #url(r'^search/?$', 'search'),
    #url(r'^lookup/?$', 'lookup'),
    url(r'^teachers/?$', 'lookup'),
    # url(r'^teachers1/?$', 'lookup1'),
    url(r'^attendance/?$', 'attendance', name='attendance' ),
    url(r'^submit_attendance/?$', 'submit_attendance'),
    url(r'myevidyaloka/?$', 'myevidyaloka', name = 'myevidyaloka' ),
    url(r'myevidyaloka/contributions/?$', 'my_contributions', name = 'my_contributions'),
    url(r'^mystudents/?$', 'mystudents'),
    url(r'^attendance_mystudents/?$', 'attendance_mystudents'),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'', include('social_auth.urls')),
    url(r'^notification/?', include('notification.urls')),
    url(r'admindash/?$', 'admindash', name='admindash'),
    url(r'^centeradmin/?$', 'centeradmin', name='centeradmin'),
    url(r'^publish/?$', 'publish', name='publish'),
    url(r'^allocate/?$', 'allocate', name='allocate'),
    url(r'create_offering/?$', 'create_offering', name='create_offering'),
    #url(r'centerassign/?$', 'centerassign', name='centerassign'),
    #url(r'centerassign/?$', 'assign_offer'),
    url(r'myteachers/?$', 'myteachers', name='myteachers'),
     
    url(r'teacherdash/?$', 'teacherdash', name='teacherdash'),
    url(r'^contentadmin/?$', 'contentadmin', name='contentadmin'),
    url(r'^content_lookup/?$', 'content_lookup', name='clookup'),
    url(r'^get_topics/?$', 'get_topics', name='get_topics'),
    url(r'^get_content_lookup/?$', 'get_content_lookup', name='get_content_lookup'),
    url(r'claim_topic/?$', 'claim_topic', name='claim_topics'),
    url(r'^get_volunteers_topics/?$', 'get_volunteers_topics', name='get_volunteers_topics'),
    url(r'centeradmin_temp/?$', 'centeradmin_temp'),
    url(r'well_wisher/?$', 'well_wisher'),
    url(r'content_developer/?$', 'content_developer'),
    #url(r'fund_raiser/?$', 'fund_raiser'),
    #url(r'it_developer/?$', 'it_developer'),
    url(r'assignoffer/?$', 'assign_offer'),
    url(r'get_events/?$', 'get_events'),
    url(r'get_event/?$', 'get_event'),
    url(r'get_teachers/?$', 'get_teachers'),
    url(r'get_offerings/?$', 'get_offerings'),
    url(r'^get_centeroffering/?$', 'get_centeroffering'),
    url(r'^active_map/?$', 'active_cities_map', name='active_map'),
    url(r'^map/?$', 'draw_map', name='map'),
    url(r'^add_session/?$', 'add_session'),
    #url(r'^accounts/register/?$', register, {'form_class':RegistrationFormUniqueEmail, 'backend':'registration.backends.default.DefaultBackend' }, name='registration_register'),
    url(r'^accounts/register/?$', 'register_dummy_method'),
    url(r'^accounts/password/reset/?$', 'password_reset'),
    url(r'^accounts/password/reset/done/?$', password_reset_done, {'template_name': 'registration/_password_reset_done.html'}),
    url(r'^accounts/password/reset/confirm/?$', password_reset_confirm, {'template_name': 'registration/_password_reset_confirm.html'}),
    url(r'^accounts/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/?$', password_reset_confirm, {'template_name': 'registration/_password_reset_confirm.html'}),
    url(r'^accounts/password/reset/complete/?$', password_reset_complete, {'template_name': 'registration/_password_reset_complete.html'}),
    url(r'^accounts/?', include('registration.backends.default.urls')),
    # url(r'^evd/?', include('evd.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/?', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/?', include(admin.site.urls)),
    #url(r'^userprofile/?$', 'user_profile', name='home'),
    url(r'^user_profile/?$', 'new_profile', name='home'),
    url(r'^offerings/?$', 'offerings', name='home'),
    url(r'^preferences/?$', 'preferences', name='home'),
    url(r'^vision/?$', 'vision', name='home'),
    url(r'^operating_principles/?$', 'operating_principles', name='home'),
    url(r'^contact_us/?$', 'contact_us', name='home'),
    url(r'^about/?$', 'about_us', name='home'),
    url(r'^newsletter/?$', 'newsletter', name='newsletter'), #added
    url(r'^how/?$','learn_more', name='home'), #added
    url(r'^under_construction/?$','under_construction', name='home'), #added
    
    #url(r'^demand/?$','demand_new', name='home'), #added
    url(r'^demand/?$', RedirectView.as_view(url='/v2/demand')),
    
    url(r'^who_we_are/?$', 'who_we_are', name='home'),
    url(r'^sponsor/?$', 'donations', name='home'),
    url(r'^sponsor/payment_details/?$', 'payment_details', name='home'),
    url(r'^payment_request/?$', 'donate_online', name='home'), # Testing URL
    url(r'^payment_response/?$', 'donation_online_response', name='home'), #Testing URL
    url(r'^sponsor/onlinepayments/?$', 'donate_online', name='home'),
    url(r'^sponsor/thankyou/?$', 'donation_response', name='home'),
    url(r'^donations/?$', 'donations', name='home'),
    url(r'^conduct/?$', 'conduct', name='home'),
    url(r'^intro/?$', 'intro', name="home"),
    url(r'^skype/?$', 'skype', name="home"),
    url(r'^mybook/?$', 'mybook', name="home"),
    url(r'^selfpaced/?$', 'selfpaced', name="selfpaced"),
    url(r'^aidsntools/?$', 'aidsntools', name="aidsntools"),
    url(r'^curriculumreview/?$', 'curriculumreview', name='curriculumreview'),
    url(r'^code_conduct/?$', 'code_conduct', name="home"),
    url(r'^centers/?$', 'schools', name="test"),
    url(r'^spread/?$', 'spread_word', name="test"),
    #url(r'^volunteer/?$', 'spend_some_Time', name="test"),
    url(r'^download_pdf/?$', 'download_view', name='download_view'),
    url(r'^getcenters/?$', 'getcenters', name="test"),
    #url(r'^$', 'footerlinks', name="home"),
    url(r'^add_pref_course/?$', 'add_pref_course'),
    url(r'^add_dynamic_session/?$', 'add_dynamic_session'),
    url(r'^get_attendance/?$', 'get_attendance'),
    url(r'^get_feedback/?$', 'get_feedback'),
    url(r'^centeradmin_reco/?$', 'centeradmin_reco'),
    url(r'^current_sessions/?$', 'current_sessions'),
    url(r'^modify_session/?$', 'modify_session'),
    url(r'^add_course/?$', 'add_course'),
    url(r'^get_planned_topics/?', 'get_planned_topics'),
    url(r'^get_students/?', 'get_students'),
    url(r'^get_comments/?', 'offering_comment',name='offering_comment'),
    #url(r'^donate/?$', 'donate'),
    url(r'^pledge/?$', 'pledge'),
    url(r'^update_pledge/?$', 'update_pledge'),
    url(r'^donors/?$', 'donors'),
    url(r'^donorupdate/?$', 'donor_update'),
    url(r'^partners/?$', 'partners',name='partners'),
    url(r'^careers/?$', 'careers',name='careers'),
    url(r'complete_offering/?', 'complete_offering'),
    #url(r'news_events/?$', 'news_events', name='news_events'),
    url(r'^governance/?$', 'governance', name='governance'),
    url(r'^stats/?$', 'stats', name='stats'),
    url(r'^policies/?$', 'privacy_policies', name='privacy_policies'),
    url(r'^upload_profilepic/?$', 'upload_profilepic'),
    # url(r'^teachersday14/?$', 'teachersday14'),
    url(r'^policies_terms_conditions/?$', 'policies_terms_conditions', name='policies_terms_conditions'),
    url(r'^donor_updates/(?P<q>\d+)/?$', 'donor_updates', name='donor_updates'),
    url(r'^myclass/?$', 'myclass', name='myclass'),
    url(r'^myclassevents/?$', 'getmy_events', name='getmy_events'),
    url(r'^forums/?$', 'forum', name='forum'),
    url(r'^request_for_proposal/?$', 'rfp', name='rfp'),
    url(r'^bulk_donate/?$', 'bulk_donate', name='bulk_donate'),
    url(r'^b_pledge/?$', 'b_pledge', name='b_pledge'),
    url(r'^bulk_pledge/?$', 'bulk_pledge', name='bulk_pledge'),
    url(r'^donate_dash/?$', 'donate_dash', name='donate_dash'),
    url(r'^update_pledge_admin/?$', 'update_pledge_admin', name='update_pledge_admin'),
    url(r'^ajax/refer/?$', 'get_refer', name='get_refer'),
    url(r'^load_receipts/?$', 'load_receipts', name='load_receipts'),
    url(r'^mytrainings/?$', 'mytrainings', name='mytrainings'),
    url(r'^mark_complete/?$', 'training_complete', name='training_complete'),
    url(r'^get_calenders/?$', 'get_calenders', name='get_calenders'),
    url(r'^apply_calender/?$', 'apply_calender', name='apply_calender'),
    url(r'^get_slots/?$', 'get_slots', name='get_slots'),
    url(r'^grab_slot/?$', 'grab_slot', name='grab_slot'),
    url(r'^waiting_to_learn/?$', 'demand', name='demand'),
    url(r'^my_students/(?P<tab_id>\w+)?$', 'my_students', name='my_students'),
    url(r'^get_off_stud/?$', 'get_off_stud', name='get_off_stud'),
    url(r'^get_scholastic/?$', 'get_scholastic', name='get_scholastic'),
    url(r'^get_scholastic_lfh/?$', 'get_scholastic_lfh', name='get_scholastic'),
    url(r'^get_month_attend/?$', 'get_month_attend', name='get_month_attend'),
    url(r'^get_appreciation_reason/?$', 'get_appreciation_reason', name='get_appreciation_reason'),
    url(r'^get_co_schol/?$', 'get_co_schol', name='get_co_schol'),
    url(r'^update_lrs/?$', 'update_lrs', name='update_lrs'),
    url(r'^get_activities/?$', 'get_activities', name='get_activities'),
    url(r'^get_uniquec/?$', 'get_uniquec', name='get_uniquec'),
    url(r'^update_cosch/?$', 'update_cosch', name='update_cosch'),
    url(r'^update_act/?$', 'update_act', name='update_act'),
    url(r'^update_uc/?$', 'update_uc', name='update_uc'),
    url(r'^add_lr/?$', 'add_lr', name='add_lr'),
    url(r'^get_diagnostics/?$', 'get_diagnostics', name='get_diagnostics'),
    url(r'^lr_bulk_upload/?$', 'lr_bulk_upload', name='lr bulk upload'),
    url(r'^get_offers/?$', 'get_offers', name='get_offers'),
    url(r'^get_temp/?$', 'get_temp', name='get_temp'),
    url(r'^process_excel/?$', 'process_excel', name='get_temp'),
    url(r'^bulk_schol/?$', 'bulk_schol', name='bulk_schol'),
    url(r'^bulk_coschol/?$', 'bulk_coschol', name='bulk_coschol'),
    url(r'^bulk_diag/?$', 'bulk_diag', name='bulk_diag'),
    url(r'^get_diag_params/?$', 'get_diag_params', name='get_diag_params'),
    url(r'^add_diagnostic/?$', 'add_diagnostic', name='add_diagnostic'),
    url(r'^update_diag/?$', 'update_diag', name='update_diag'),
    #url(r'^campaign/?$', 'campaign', name='campaign'),
    url(r'^volunteer_db/?$', 'volunteer_search', name='volunteer_search'),
    url(r'^get_vol_data/?$', 'get_vol_data', name='get_vol_data'),
    url(r'^get_vol_details/?$', 'get_vol_details', name='get_vol_details'),
    url(r'^get_master_db/?$', 'get_master_db', name='get_master_db'),
    url(r'^update_vol_status/?$', 'update_vol_status', name='update_vol_status'),
    url(r'^api/', include('api.urls')),
    url(r'^workplace/', include('workplace.urls')),
    url(r'^get_ofr_sess/', 'get_ofr_sess', name='get_ofr_sess'),
    url(r'^reschedule_course/', 'reschedule_course', name='reschedule_course'),
    url(r'^bulk_usergen_xlrd/', 'bulk_usergen_xlrd', name='bulk_usergen_xlrd'),
    url(r'^bulk_usergen/', 'bulk_usergen', name='bulk_usergen'),
    url(r'^bulk_user_create/', 'bulk_user_create', name='bulk_user_create'),
    # url(r'^partner/(?P<partner_id>\w+)/?$', 'partner', name='partner'),
    url(r'^demand_new/?', 'demand_new', name='demand_new'),
    
    #url(r'^get_demand/?', 'get_demand', name='get_demand'),
    
    url(r'^demand_detail/(?P<center_id>\d+)/?$', 'demand_detail', name='demand_detail'),
    url(r'^block_demand/?', 'block_demand', name='block_demand'),
    url(r'^release_demand/?', 'release_demand', name='release_demand'),
    url(r'^confirm_accept_or_reject_slot/?', 'confirm_accept_or_reject_slot', name='accept_or_reject_slot'),
    url(r'^report_card/(?P<student_id>\d+)/$', 'report_card', name='report_card'),
    url(r'^get_reports/?', 'get_reports', name='get_reports'),
    url(r'^get_active_centers/?', 'get_active_centers', name='get_active_centers'),
    url(r'^download_report_card/?', 'download_report_card', name='download_report_card'),
    url(r'^content_upload/?', 'content_upload', name='content_upload'),
    url(r'^teachersday2016/souvenir/?$', 'teachers_day2016', name='teachers_day2016'),
    url(r'^save_profilepic/?', 'save_profilepic', name='save_profilepic'),
    url(r'^profile/?', 'new_profile', name='new_profile'),
    url(r'^save_base_profile/?', 'save_base_profile', name='save_base_profile'),
    url(r'^onboarding/?', 'onboarding', name='onboarding'),
    url(r'^role_onboarding/(?P<role_name>\w+)/?$', 'role_onboarding', name='role_onboarding'),
    url(r'^dashboard/(?P<role_name>\w+)/?$', 'role_dashboard', name='role_dashboard'),
    url(r'^selfeval_response/?', 'selfeval_response', name='selfeval_response'),
    url(r'^save_availability/?', 'save_availability', name='save_availability'),
    url(r'^save_step/?', 'save_step', name='save_step'),
    url(r'^render_demand/?', 'render_demand', name='render_demand'),
    url(r'^engage/?', 'evd_fb_feed', name='evd_fb_feed'),
    url(r'^se_response_sheet/?', 'se_response_sheet', name='se_response_sheet'),
    url(r'^gcalender_api_callback/?', 'gcalender_api_callback', name='gcalender_api_callback'),
    #url(r'^rubaru17/?', 'rubaru_main', name='rubaru_main'),
    url(r'^rubaru_register/?', 'rubaru_register', name='rubaru_register'),
    url(r'^save_slots/?', 'save_slots', name='save_slots'),
    url(r'^delete_slots/?', 'delete_slots', name='delete_slots'),
    url(r'^publish_slots/?', 'publish_slots', name='publish_slots'),
    url(r'^save_publish_slots/?', 'save_publish_slots', name='save_publish_slots'),
    url(r'^delete_publish_slots/?', 'delete_publish_slots', name='delete_publish_slots'),
    url(r'^book_sd_slots/?', 'book_sd_slots', name='book_sd_slots'),
    url(r'^book_or_release_sd_slot/?', 'book_or_release_sd_slot', name='book_or_release_sd_slot'),
    url(r'get_sd_slot_details/?', 'get_sd_slot_details', name='get_sd_slot_details'),
    url(r'^volunteer_heatmap/?', 'volunteer_heatmap', name='volunteer_heatmap'),
    url(r'^get_filters_api/?', 'get_filters_api'),
    url(r'^demand_details_api/(?P<center_id>\d+)/?$', 'demand_details_api', name='demand_details_api'),
    url(r'^redirect/?', 'url_redirect', name='redirect'),
    url(r'^get_session_details/?$', 'get_session_details', name='get_session_details'),
    url(r'^task_list/?', 'task_list', name='task_list'),
    url(r'^ajax/task_list/?', 'getTaskListData', name='getTaskListData'),
    url(r'^saveTask/?$', 'saveTask', name='saveTask'),
    url(r'^updateTask/?$', 'updateTask', name='updateTask'),
    url(r'^create_task/?$', 'create_task',name='create_task'),
    url(r'^students_dashboard/?$', 'students_dashboard', name='students_dashboard'),
    url(r'^task_list/?', 'task_list', name='task_list'),
    url(r'^edit_task/?$', 'edit_task',name='edit_task'),
    url(r'^activities/?','activities',name='activities'),
    url(r'^students_progress_report/?', 'students_progress_report', name='students_progress_report'),
    url(r'^reportCard/?', 'reportCard', name='reportCard'),
    url(r'^ajax/getCourses/?', 'get_Courses', name='get_Courses'),
    url(r'^ajax/get_Students_for_report_card/?', 'get_Students_for_report_card', name='get_Students_for_report_card'),
    url(r'^ajax/getgradeforReortCard/?', 'getgradeforReortCard', name='getgradeforReortCard'),
    url(r'^ajax/getTableList/?', 'students_progress_report', name='students_progress_report'),
    url(r'^ajax/update_role_or_status/?', 'update_user_Role_or_status', name='update_user_Role_or_status'),
    url(r'^get_quiz_result/?', 'get_quiz_result', name='get_quiz_result'),

    url(r'^get_award_nominees/?', 'get_award_nominees', name='get_award_nominees'),
    url(r'^save_nomination/?', 'save_nomination', name='save_nomination'),
    url(r'^review_awards/?', 'review_awards', name='review_awards'),
    url(r'^get_location_data/?', 'get_location_data', name='get_location_data'),
    url(r'^setting/?', 'my_setting', name='my_setting'),
    url(r'^userActivity/?', 'userActivity', name='userActivity'),
    url(r'^saveSettings/?', 'saveSettings', name='saveSettings'),
    url(r'^ajax/getyearfor_student/?', 'getyearfor_student', name='getyearfor_student'),
    url(r'^system_generated_task/>', 'system_generated_task', name='system_generated_task'),
    url(r'^ajax/save_user_activity_by_ajax/?', 'save_user_activity_by_ajax', name='save_user_activity_by_ajax'),
    url(r'^ajax/update_assignee/?', 'update_assignee', name='update_assignee'),
    url(r'^get_certificate/?', 'get_certificate', name='get_certificate'),
    url(r'^my_certificate/?', 'my_certificate', name='my_certificate'),
    url(r'^teacher_certificate/?', 'my_certificate', name='my_certificate'),
    url(r'^ajax/userActivityHistoryFilter/?', 'userActivityHistoryFilter', name='userActivityHistoryFilter'),
    url(r'^ajax/get_grade/?', 'get_grade', name='get_grade'),
    url(r'^ajax/getActivityNameByActivityType/?', 'getActivityNameByActivityType', name='getActivityNameByActivityType'),
    url(r'^ajax/userActivityFilter/?', 'userActivityFilter', name='userActivityFilter'),
    url(r'^approve_offering/?', 'approve_offering', name='approve_offering'),
    url(r'^ajax/updateOfferingOrOthersStatus/?', 'updateOfferingOrOthersStatus', name='updateOfferingOrOthersStatus'),
    url(r'^ajax/verifyUserForTSD/?', 'verifyUserForTSD', name='verifyUserForTSD'),
    # url(r'^partner_onboard/?', include('partner.urls')),
    url(r'^partner/?', include('partner.urls')),
    #url(r'^funding_parter/?', 'funding_parter', name='funding_parter'),
    url(r'^volunteer_partner/?', 'volunteer_partner', name='volunteer_partner'),
    url(r'^volunteer-signup/?', 'campaign', name='campaign'),
    url(r'^volunteer/?', 'new_profile', name="new_profile_page"),
    url(r'^volunteer_signup.html', 'campaign', name='campaign'),
    #  url(r'^evschool/', 'evschool', name='evschool'),
    url(r'^digital_school/', 'digitalSchool', name='digitalschool'),
    #url(r'^campaign_signup/?', 'campaign_signup', name='campaign_signup'),
    url(r'^campaign/?', 'nad_campaign', name='nad_campaign'),
    url(r'^v2/?', include('webext.urls')),
    url(r'^rubaru/?', TemplateView.as_view(template_name='rubaru2022.html'), name='rubaru'),
    url(r'^springboard/?', TemplateView.as_view(template_name='springboard.html'), name='springboard'),
    url(r'^nsic/?',TemplateView.as_view(template_name='nsic.html'), name="nsic_home"),
    url(r'^app_privacy/?',TemplateView.as_view(template_name='app_privacy.html'), name="app_privacy")
)

urlpatterns = urlpatterns + patterns('',
    url(r'', include('web.urls')),
    url(r'^projectsummary/', 'web.views.projectsummary',name='projectsummary'),
    url(r'^projectsummary_details','web.views.projectsummarydetail', name="projectsummarydetail"),
    url(r'^rest_authentication/?', include('rest_authentication.urls')),
    url(r'^school/search/?$', get_partner_school, name='get_partner_school'),
    url(r'^/?$', 'web.views.new_home',name="homepage"),
    url(r'^config/', include('configs.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps, 'template_name': 'sitemap.html'}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots', lambda x: HttpResponse(open('robots.txt', 'rb'), content_type="text/plain"), name="robots_file"),
    url(r'^evplus/?', TemplateView.as_view(template_name='evplus.html'), name='evplus'),
    url(r'^questions/', include('questionbank.urls')),
    url(r'^student/?', include('student.urls')),
)

(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve',
               {'document_root': settings.ADMIN_MEDIA_PREFIX})

(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.STATIC_ROOT})
