# -*- coding: utf-8 -*-

USER_DATA_TEACHERS_DAY_2016 = {
  "45": { "teacher":"Ajeet Kumar", "grade":"6th", "center":"Bero", "city":"Grenoble", "state":"JH", "sponsor":"BGMRT", "pic":"6thhira.jpg"},
  "53": { "teacher":"Aastha Bhartia", "grade":"5th", "center":"Sonbad", "city":"Bangalore", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "119": { "teacher":"Arun R", "grade":"7th", "center":"Itki", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "155": { "teacher":"Gomathi", "grade":"6th", "center":"Topslip", "city":"Kalpakkam", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "159": { "teacher":"Renganayaki", "grade":"7th", "center":"Topslip", "city":"NEYVELI", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "230": { "teacher":"Srimathi", "grade":"6th", "center":"Aravenu", "city":"coimbatore", "state":"TN", "sponsor":"", "pic":"6th.png"},
  "311": { "teacher":"Anuradha Jagadeesan", "grade":"6th", "center":"Hanumasagara", "city":"Reykjavik,Iceland", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "322": { "teacher":"Arvind ", "grade":"6th", "center":"Keradamattam", "city":"Chennai", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "357": { "teacher":"Sujatha", "grade":"6th", "center":"Esanaikorai", "city":"Warsaw", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "408": { "teacher":"Mohan", "grade":"7th", "center":"Kishikindapalem", "city":"Hyderabad", "state":"AP", "sponsor":"Raman A.", "pic":"7th.jpg"},
  "424": { "teacher":"Nishtha Sharma", "grade":"6th", "center":"Itki", "city":"Sydney", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "466": { "teacher":"As roa", "grade":"6th", "center":"Chittela", "city":"chennai", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "513": { "teacher":"Pratima", "grade":"7th", "center":"Rolupadi", "city":"Philadelphia", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "588": { "teacher":"Rosario", "grade":"6th", "center":"Aravenu", "city":"coimbatore", "state":"TN", "sponsor":"", "pic":"6th.png"},
  "616": { "teacher":"Srutha", "grade":"6th", "center":"Juvalepalem", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "645": { "teacher":"Anshuman", "grade":"8th", "center":"Chachgura", "city":"Fargo, United States", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "670": { "teacher":"Reshma", "grade":"7th", "center":"Baad", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "691": { "teacher":"Prasad", "grade":"5th", "center":"Sathamangala", "city":"Santa Clara", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "744": { "teacher":"Elavarasan", "grade":"7th", "center":"Sathamangala", "city":"Dubai", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "921": { "teacher":"Sriram", "grade":"7th", "center":"Mallella", "city":"Piscataway", "state":"AP", "sponsor":"", "pic":"7thm.jpg"},
  "955": { "teacher":"Shubhangi", "grade":"7th", "center":"Chachgura", "city":"Mumbai", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "1149": { "teacher":"Archana", "grade":"7th", "center":"Esanaikorai", "city":"Magdeburg, Germany", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "1165": { "teacher":"Anjana", "grade":"5th", "center":"Chachgura", "city":"Delhi", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "1208": { "teacher":"Abhishek Sharma", "grade":"7th", "center":"Bero", "city":"Panipat", "state":"JH", "sponsor":"BGMRT", "pic":"7thhira.jpg"},
  "1246": { "teacher":"Somya Awasthi", "grade":"6th", "center":"Koymara", "city":"new delhi", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "1262": { "teacher":"Chandra", "grade":"7th", "center":"Semmambadi", "city":"Chennai", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "1273": { "teacher":"Sasmita Kant Maurya", "grade":"7th", "center":"Sonbad", "city":"Jammu(Udhampur)", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "1341": { "teacher":"Pushpa", "grade":"5th", "center":"Topslip", "city":"New Zealand", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "1352": { "teacher":"Tejo Karthik", "grade":"7th", "center":"Mallella", "city":"Sunnyvale", "state":"AP", "sponsor":"", "pic":"7thv.jpg"},
  "1425": { "teacher":"Vidya kv", "grade":"7th", "center":"Lakshmipuram", "city":"Sunnyvale", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "1427": { "teacher":"Renuka", "grade":"7th", "center":"Mallella", "city":"hyderabad", "state":"AP", "sponsor":"", "pic":"7thv.jpg"},
  "1493": { "teacher":"Raghav", "grade":"7th", "center":"Keradamattam", "city":"Wellington", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "1592": { "teacher":"Gargi Singh", "grade":"5th", "center":"Sonbad", "city":"Farrukhabad", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "1678": { "teacher":"Meenakshi Babu", "grade":"7th", "center":"Esanaikorai", "city":"Bangalore", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "1731": { "teacher":" Bindu Jose Roy", "grade":"5th", "center":"Hanumasagara", "city":"christchurch", "state":"KA", "sponsor":"L&T Infotech", "pic":"5th.jpg"},
  "1740": { "teacher":"Jasantha", "grade":"6th", "center":"Konijerla", "city":"Others", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "1752": { "teacher":"Deva", "grade":"7th", "center":"Ariyur", "city":"Irvine", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "1761": { "teacher":"Ramya", "grade":"7th", "center":"Hanumasagara", "city":"Blaine", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "1789": { "teacher":"Hemamalini", "grade":"5th", "center":"sulligondu", "city":"Trivandrum", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "1898": { "teacher":"Ashish Shavarna", "grade":"6th", "center":"Bero", "city":"Hillsboro, Oregon, US", "state":"JH", "sponsor":"BGMRT", "pic":"6thhira.jpg"},
  "1906": { "teacher":"Jayashree", "grade":"7th", "center":"Baad", "city":"Delhi", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "1923": { "teacher":"Priyanka Joshi", "grade":"8th", "center":"Sonbad", "city":"Cambridge", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "2006": { "teacher":"Srivatsan", "grade":"7th", "center":"Aravenu", "city":"Gainesville", "state":"TN", "sponsor":"", "pic":"7th.png"},
  "2047": { "teacher":"Janaki", "grade":"6th", "center":"Keradamattam", "city":"Muscat", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "2105": { "teacher":"Uma Sathvi", "grade":"5th", "center":"Gosaveedu", "city":"Atlanta, GA", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "2467": { "teacher":"yeshashwini", "grade":"5th", "center":"Hanumasagara", "city":"Wellington", "state":"KA", "sponsor":"L&T Infotech", "pic":"5th.jpg"},
  "2572": { "teacher":"Prasad", "grade":"6th", "center":"Lakshmipuram", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "2582": { "teacher":"Sushil Grover", "grade":"5th", "center":"Koyritola", "city":"Weston", "state":"JH", "sponsor":"Sampath S.", "pic":"5th.jpg"},
  "2674": { "teacher":"Ramesh", "grade":"8th", "center":"Vamakuntala", "city":"Doha, Qatar", "state":"AP", "sponsor":"Manish Kotwala", "pic":"8th.jpg"},
  "2715": { "teacher":"Usha Sekhar", "grade":"7th", "center":"Shitalpur", "city":"Bangalore", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "2787": { "teacher":"Bhagyalakshmi", "grade":"8th", "center":"Chittela", "city":"chirala", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "2816": { "teacher":"Smitha Ravikumar", "grade":"6th", "center":"Udnabad", "city":"Bangalore", "state":"JH", "sponsor":"Satish V", "pic":"6th.jpg"},
  "2821": { "teacher":"Karthik", "grade":"5th", "center":"Esanaikorai", "city":"Chennai", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "2938": { "teacher":"Rahul", "grade":"7th", "center":"Shitalpur", "city":"Trivandrum", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "2939": { "teacher":"Sugandha Agarwal", "grade":"7th", "center":"Koyritola", "city":"bangalore", "state":"JH", "sponsor":"Sampath S.", "pic":"7th.jpg"},
  "2943": { "teacher":"saisirisha", "grade":"7th", "center":"Mallella", "city":"Kadapa", "state":"AP", "sponsor":"", "pic":"7thv.jpg"},
  "2974": { "teacher":"Nalini", "grade":"6th", "center":"Koyritola", "city":"singapore", "state":"JH", "sponsor":"Sampath S.", "pic":"6th.jpg"},
  "2993": { "teacher":"Kavya", "grade":"6th", "center":"Juvalepalem", "city":"Austin", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "3000": { "teacher":"Diya Gangopadhyay", "grade":"7th", "center":"Mirzaganj", "city":"New York", "state":"JH", "sponsor":"WilliamsLea ", "pic":"7th.jpg"},
  "3011": { "teacher":"Deekshitulu", "grade":"6th", "center":"Lakshmipuram", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "3069": { "teacher":"Ushashree", "grade":"6th", "center":"Mallella", "city":"Santa Barbara", "state":"AP", "sponsor":"", "pic":"6thv.jpg"},
  "3119": { "teacher":"Gouthami", "grade":"5th", "center":"Lakshmipuram", "city":"Visakhapatnam", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "3171": { "teacher":"Anshika Katara", "grade":"7th", "center":"Koyritola", "city":"BANGALORE", "state":"JH", "sponsor":"Sampath S.", "pic":"7th.jpg"},
  "3178": { "teacher":"Darpan Jha", "grade":"6th", "center":"Mirzaganj", "city":"Bangalore", "state":"JH", "sponsor":"WilliamsLea ", "pic":"6th.jpg"},
  "3358": { "teacher":"Sneha", "grade":"6th", "center":"Shitalpur", "city":"San Francisco", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "3366": { "teacher":"Soumya Samanthray", "grade":"6th", "center":"Jhalakdiha", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "3381": { "teacher":"Usha Rao", "grade":"5th", "center":"Baad", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"5th.jpg"},
  "3419": { "teacher":"Rahul Roshan", "grade":"6th", "center":"Chachgura", "city":"Bangalore", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "3452": { "teacher":"Meenakshi", "grade":"5th", "center":"Aravenu", "city":"Dubai", "state":"TN", "sponsor":"", "pic":"5th.png"},
  "3513": { "teacher":"Mansa Bhagavatula", "grade":"5th", "center":"Udnabad", "city":"El Dorado Hills", "state":"JH", "sponsor":"Satish V", "pic":"5th.jpg"},
  "3535": { "teacher":"Sridivya", "grade":"6th", "center":"Kishikindapalem", "city":"Seattle", "state":"AP", "sponsor":"Raman A.", "pic":"6th.jpg"},
  "3555": { "teacher":"Rupika", "grade":"7th", "center":"Chachgura", "city":"delhi", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "3582": { "teacher":"Rajesh", "grade":"7th", "center":"Ariyur", "city":"chennai", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "3684": { "teacher":"Arpana", "grade":"6th", "center":"Benakanakatti", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "3701": { "teacher":"Harika", "grade":"7th", "center":"Vamakuntala", "city":"Cambridge, U.K.", "state":"AP", "sponsor":"Manish Kotwala", "pic":"7th.jpg"},
  "3745": { "teacher":"Sandhya Balakrishnan", "grade":"7th", "center":"Managundi", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":""},
  "3773": { "teacher":"Anandhi", "grade":"5th", "center":"sulligondu", "city":"Kuala Lumpur", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "3835": { "teacher":"Kala Ganesh", "grade":"7th", "center":"Keradamattam", "city":"BENGALURU", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "3835": { "teacher":"Kala Ganesh", "grade":"6th", "center":"Sathamangala", "city":"BENGALURU", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "3868": { "teacher":"Vijayashree", "grade":"5th", "center":"Topslip", "city":"Hyderabad", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "3928": { "teacher":"Smriti Jha", "grade":"7th", "center":"Mirzaganj", "city":"hyderabad", "state":"JH", "sponsor":"WilliamsLea ", "pic":"7th.jpg"},
  "3973": { "teacher":"Dr.Anupama Gupta", "grade":"6th", "center":"Chengarbasa", "city":"Moradabad", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"6th.jpg"},
  "3991": { "teacher":"Chiranjeev Kumar", "grade":"7th", "center":"Itki", "city":"Delhi", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "4161": { "teacher":" Sunanda", "grade":"7th", "center":"Hosadurga", "city":"Bangalore", "state":"KA", "sponsor":"Infosys BPO", "pic":""},
  "4187": { "teacher":"Joy Jain", "grade":"6th", "center":"Koyritola", "city":"Chennai", "state":"JH", "sponsor":"Sampath S.", "pic":"6th.jpg"},
  "4192": { "teacher":"Neeraja", "grade":"5th", "center":"Chachgura", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "4195": { "teacher":"laxmi Sharma", "grade":"7th", "center":"Mirzaganj", "city":"Chennai", "state":"JH", "sponsor":"WilliamsLea ", "pic":"7th.jpg"},
  "4198": { "teacher":"Suja", "grade":"6th", "center":"Ariyur", "city":"ankleshwar", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "4279": { "teacher":"Sweeta Jain", "grade":"7th", "center":"Koyritola", "city":"Chennai", "state":"JH", "sponsor":"Sampath S.", "pic":"7th.jpg"},
  "4310": { "teacher":"srikiran", "grade":"6th", "center":"Lakshmipuram", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "4319": { "teacher":"Abhijit Manna", "grade":"6th", "center":"Dumdumi", "city":"Joka", "state":"WB", "sponsor":"Dubai Chapter", "pic":"6th.jpg"},
  "4345": { "teacher":"Anika", "grade":"7th", "center":"Chachgura", "city":"Bhopal", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "4365": { "teacher":"Amit Kumar Gupta", "grade":"6th", "center":"Chengarbasa", "city":"Hyderabad", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"6th.jpg"},
  "4410": { "teacher":"Prachi Randhawa", "grade":"8th", "center":"Jhalakdiha", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "4485": { "teacher":"Indu Nair", "grade":"7th", "center":"Udnabad", "city":"Mississauga, ONTARIO, Canada", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "4486": { "teacher":"Sony Doshi", "grade":"6th", "center":"Chachgura", "city":"Rajkot", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "4513": { "teacher":"Rajalakshmi Raj", "grade":"7th", "center":"Chengarbasa", "city":"bangalore", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"7th.jpg"},
  "4626": { "teacher":"Gayathri S", "grade":"5th", "center":"Esanaikorai", "city":"Chennai", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "4631": { "teacher":"dilip", "grade":"7th", "center":"Chittela", "city":"Cape town", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "4668": { "teacher":"Srikanth", "grade":"Centre Admin", "center":"Vamakuntala", "city":"Guntur", "state":"AP", "sponsor":"Manish Kotwala", "pic":"6th.jpg"},
  "4668": { "teacher":"Srikanth", "grade":"7th", "center":"Vamakuntala", "city":"Guntur", "state":"AP", "sponsor":"Manish Kotwala", "pic":"7th.jpg"},
  "4674": { "teacher":"Gowri", "grade":"8th", "center":"Rolupadi", "city":"Dallas", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "4725": { "teacher":"Rudrakanth sollapur", "grade":"6th", "center":"Managundi", "city":"Jena", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "4729": { "teacher":"Pawan rathi", "grade":"5th", "center":"Jhalakdiha", "city":"Delhi", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "4744": { "teacher":"Vamsi", "grade":"8th", "center":"Gosaveedu", "city":"Smyrna", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "4819": { "teacher":"Kullai Thotamsetty", "grade":"6th", "center":"Mallella", "city":"Bengaluru", "state":"AP", "sponsor":"", "pic":"6thm.jpg"},
  "4821": { "teacher":"Sumita Biswas", "grade":"", "center":"Bengabad", "city":"New Delhi", "state":"JH", "sponsor":"", "pic":""},
  "4858": { "teacher":"Shravya", "grade":"7th", "center":"Juvalepalem", "city":"hyderabad", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "4872": { "teacher":"Pradeepti Inapakurti", "grade":"6th", "center":"Bero", "city":"Hyderabad", "state":"JH", "sponsor":"BGMRT", "pic":"6thmoti.jpg"},
  "4876": { "teacher":"Prashanth", "grade":"6th", "center":"Gosaveedu", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "4886": { "teacher":"Sasidhar", "grade":"6th", "center":"Konijerla", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "4972": { "teacher":"Priya Aditya", "grade":"7th", "center":"Baad", "city":"Singapore", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "5001": { "teacher":"Swarna", "grade":"5th", "center":"Konijerla", "city":"Bengaluru", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "5027": { "teacher":"Chenna Jaya", "grade":"7th", "center":"Gosaveedu", "city":"bangalore", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "5104": { "teacher":"Bhavana Chaturvedi", "grade":"7th", "center":"Chengarbasa", "city":"Ghaziabad", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"7th.jpg"},
  "5129": { "teacher":"Akshatha Nayak", "grade":"5th", "center":"Chachgura", "city":"Udupi", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "5141": { "teacher":"Karthik Parashar", "grade":"6th", "center":"Managundi", "city":"Leuven", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "5200": { "teacher":"Sirisha", "grade":"Centre Admin", "center":"Rolupadi", "city":"bengaluru", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "5200": { "teacher":"Sirisha", "grade":"5th", "center":"Rolupadi", "city":"bengaluru", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "5206": { "teacher":"Prasanna", "grade":"Center Admin", "center":"Gosaveedu", "city":"san francisco", "state":"AP", "sponsor":"", "pic":""},
  "5212": { "teacher":"Rajesh gandhi", "grade":"7th", "center":"Jhalakdiha", "city":"Mumbai", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "5237": { "teacher":"Bhavani", "grade":"6th", "center":"Rolupadi", "city":"Bengaluru", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "5239": { "teacher":"Nehal raja", "grade":"7th", "center":"Udnabad", "city":"Bangalore", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "5240": { "teacher":"Raghu", "grade":"8th", "center":"Gosaveedu", "city":"Bangalore", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "5255": { "teacher":"Mahathi", "grade":"7th", "center":"Gosaveedu", "city":"Natick,MA", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "5297": { "teacher":"Madhumathi", "grade":"7th", "center":"Chittela", "city":"Bangalore", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "5322": { "teacher":"Madhavi", "grade":"Centre Admin", "center":"Konijerla", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":""},
  "5322": { "teacher":"Madhavi", "grade":"7th", "center":"Konijerla", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "5332": { "teacher":"Prahlad Patki", "grade":"6th", "center":"Baad", "city":"BANGALORE", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "5364": { "teacher":"Surendranath Singh", "grade":"6th", "center":"Hanasoge", "city":"Bengaluru", "state":"KA", "sponsor":"", "pic":"6th.jpg"},
  "5384": { "teacher":"Namitha", "grade":"6th", "center":"Mugad", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "5390": { "teacher":"Srividya Srinivasaraghavan", "grade":"7th", "center":"Udnabad", "city":"Hyderabad", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "5491": { "teacher":"Lakshmi Ranganath", "grade":"7th", "center":"Benakanakatti", "city":"Bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "5579": { "teacher":"Prabhakar", "grade":"5th", "center":"Benakanakatti", "city":"Bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"5th.jpg"},
  "5613": { "teacher":"Meenakshi", "grade":"7th", "center":"Semmambadi", "city":"Bengaluru", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "5613": { "teacher":"Meenakshi", "grade":"7th", "center":"Ariyur", "city":"Bengaluru", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "5614": { "teacher":"Anantha Raushan", "grade":"6th", "center":"Itki", "city":"pune", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "5616": { "teacher":"Ganesh", "grade":"7th", "center":"Sathamangala", "city":"Chennai", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "5714": { "teacher":"Chitra Venkataraman", "grade":"5th", "center":"Udnabad", "city":"Bangalore", "state":"JH", "sponsor":"Satish V", "pic":"5th.jpg"},
  "5732": { "teacher":"Sandhya", "grade":"8th", "center":"Keradamattam", "city":"Bengaluru", "state":"TN", "sponsor":"", "pic":"8th.jpg"},
  "5741": { "teacher":"AMRATA AGRAWAL", "grade":"7th", "center":"Koymara", "city":"NAGPUR", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "5770": { "teacher":"Rashmi kapur", "grade":"5th", "center":"Koyritola", "city":"Bangkok", "state":"JH", "sponsor":"Sampath S.", "pic":"5th.jpg"},
  "5833": { "teacher":"Annapoorani", "grade":"7th", "center":"Sathamangala", "city":"Hyderabad", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "5882": { "teacher":"Deepa", "grade":"6th", "center":"sulligondu", "city":"Trichy, Tamilnadu", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "5925": { "teacher":"Sneha Sheth", "grade":"8th", "center":"Sonbad", "city":"Vancouver", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "5966": { "teacher":"Pavithra", "grade":"8th", "center":"Keradamattam", "city":"Thoobarahalli Post, Bangalore", "state":"TN", "sponsor":"", "pic":"8th.jpg"},
  "5989": { "teacher":"Prashant Saxena", "grade":"5th", "center":"Bajpur", "city":"Noida", "state":"JH", "sponsor":"Shankar A", "pic":"5th.jpg"},
  "6025": { "teacher":"Tripti Gupta", "grade":"7th", "center":"Koymara", "city":"Kiel", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "6045": { "teacher":"Saritha", "grade":"6th", "center":"Gosaveedu", "city":"hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "6101": { "teacher":"Dhatri", "grade":"7th", "center":"Rolupadi", "city":"navimumbai", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "6109": { "teacher":"Jothi", "grade":"6th", "center":"sulligondu", "city":"KOLKATA", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "6153": { "teacher":"Manisha", "grade":"6th", "center":"Baad", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "6159": { "teacher":"Gayathri", "grade":"6th", "center":"Mugad", "city":"Singapore", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "6183": { "teacher":"Thammaiah", "grade":"7th", "center":"Hanumasagara", "city":"Bangalore", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "6195": { "teacher":"Karthiga", "grade":"6th", "center":"Semmambadi", "city":"Sunnyvale", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "6236": { "teacher":"Gurudev", "grade":"6th", "center":"Benakanakatti", "city":"bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "6240": { "teacher":"SyamalaRao", "grade":"8th", "center":"Lakshmipuram", "city":"Beckenham", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "6296": { "teacher":"Shobha", "grade":"7th", "center":"Benakanakatti", "city":"Kolkata", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "6296": { "teacher":"Shobha", "grade":"7th", "center":"Thopalakatti", "city":"Kolkata", "state":"KA", "sponsor":"Infosys BPO", "pic":"7th.jpg"},
  "6303": { "teacher":"Geeta Krishnamurthy", "grade":"7th", "center":"Hanasoge", "city":"Bengaluru", "state":"KA", "sponsor":"", "pic":"7th.jpg"},
  "6303": { "teacher":"Geetha Krishnamurthy", "grade":"6th", "center":"Halagondanahalli", "city":"Bengaluru", "state":"KA", "sponsor":"Infosys BPO", "pic":"6th.jpg"},
  "6335": { "teacher":"Sowmiya", "grade":"8th", "center":"Esanaikorai", "city":"madurai", "state":"TN", "sponsor":"CAMS", "pic":"8th.jpg"},
  "6385": { "teacher":"Hima bindu", "grade":"7th", "center":"Kishikindapalem", "city":"Hyderabad", "state":"AP", "sponsor":"Raman A.", "pic":"5th.jpg"},
  "6386": { "teacher":"Bindhu", "grade":"5th", "center":"Semmambadi", "city":"Hosur", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "6386": { "teacher":"Bindhu", "grade":"5th", "center":"Semmambadi", "city":"Hosur", "state":"TN", "sponsor":"", "pic":"5th.jpg"},
  "6396": { "teacher":"Prathyusha", "grade":"7th", "center":"Juvalepalem", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "6416": { "teacher":"Smita Pathak", "grade":"7th", "center":"Bero", "city":"Secunderabad", "state":"JH", "sponsor":"BGMRT", "pic":"7thhira.jpg"},
  "6438": { "teacher":"Vijayalakshmi", "grade":"8th", "center":"Keradamattam", "city":"chennai", "state":"TN", "sponsor":"", "pic":"8th.jpg"},
  "6438": { "teacher":"Vijyalakshmi", "grade":"7th", "center":"Semmambadi", "city":"chennai", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "6450": { "teacher":"Parul Chalana", "grade":"6th", "center":"Mirzaganj", "city":"Jaipur", "state":"JH", "sponsor":"WilliamsLea ", "pic":"6th.jpg"},
  "6488": { "teacher":"Puja Goyal", "grade":"6th", "center":"Sonbad", "city":"Urbana, IL", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "6516": { "teacher":"Ashwini", "grade":"7th", "center":"Gosaveedu", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "6528": { "teacher":"Sonal", "grade":"5th", "center":"Sonbad", "city":"Mumbai", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "6602": { "teacher":"Somasundari", "grade":"7th", "center":"Aravenu", "city":"Chennai", "state":"TN", "sponsor":"CAMS", "pic":"7th.png"},
  "6621": { "teacher":"Jayanthi", "grade":"6th", "center":"sulligondu", "city":"Others", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "6636": { "teacher":"Anusha", "grade":"6th", "center":"Keradamattam", "city":"Glendale, Arizona", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "6693": { "teacher":"Sriranjini Ranga", "grade":"6th", "center":"Mirzaganj", "city":"Mumbai", "state":"JH", "sponsor":"WilliamsLea ", "pic":"6th.jpg"},
  "6708": { "teacher":"Anil samadhiya", "grade":"5th", "center":"Mirzaganj", "city":"Gwalior", "state":"JH", "sponsor":"WilliamsLea ", "pic":"5th.jpg"},
  "6709": { "teacher":"Santhanalakshmi", "grade":"7th", "center":"Keradamattam", "city":"Bellevue", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "6723": { "teacher":"Niharika Mandapakala", "grade":"6th", "center":"Mallella", "city":"Secunderabad", "state":"AP", "sponsor":"", "pic":"6thm.jpg"},
  "6779": { "teacher":"Lata Bangera", "grade":"5th", "center":"Koymara", "city":"Doha", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "6796": { "teacher":"Saraswathy", "grade":"7th", "center":"Esanaikorai", "city":"Bengaluru", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "6843": { "teacher":"Sandhya Mody", "grade":"5th", "center":"Chengarbasa", "city":"Hyderabad", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"5th.jpg"},
  "6875": { "teacher":"Chaitra Bhat", "grade":"6th", "center":"Hanasoge", "city":"Jharsuguda", "state":"KA", "sponsor":"", "pic":"6th.jpg"},
  "6897": { "teacher":"Sudha yamini", "grade":"5th", "center":"Konijerla", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "6924": { "teacher":"Divya", "grade":"6th", "center":"Sathamangala", "city":"Bengaluru", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "6926": { "teacher":"Arunkumar", "grade":"6th", "center":"Esanaikorai", "city":"Hyderabad", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "6933": { "teacher":"Sirisha", "grade":"6th", "center":"Chittela", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "6936": { "teacher":"Dileep Pasumarthi", "grade":"6th", "center":"Konijerla", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "6937": { "teacher":"Ryetika chaturvedi", "grade":"6th", "center":"Koymara", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "6939": { "teacher":"Lalita Nayal", "grade":"6th", "center":"Chachgura", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "6952": { "teacher":"Kumudha", "grade":"6th", "center":"Ariyur", "city":"Coimbatore", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "6972": { "teacher":"Samina Ali", "grade":"7th", "center":"Udnabad", "city":"Udaipur", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "6975": { "teacher":"Yamini", "grade":"7th", "center":"Mallella", "city":"Jamshedpur", "state":"AP", "sponsor":"", "pic":"7thm.jpg"},
  "6976": { "teacher":"Ankit Goel", "grade":"5th", "center":"Mirzaganj", "city":"Jamshedpur", "state":"JH", "sponsor":"WilliamsLea ", "pic":"5th.jpg"},
  "6979": { "teacher":"Pratyush Raj", "grade":"5th", "center":"Bero", "city":"Jamshedpur", "state":"JH", "sponsor":"BGMRT", "pic":"5th.jpg"},
  "6982": { "teacher":"Aritra Santra", "grade":"5th", "center":"Dumdumi", "city":"Jamshedpur", "state":"WB", "sponsor":"Dubai Chapter", "pic":"5th.jpg"},
  "6994": { "teacher":"Abhinay Sali", "grade":"7th", "center":"Lakshmipuram", "city":"Jamshedpur", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "6995": { "teacher":"Akshay Bageshwar", "grade":"5th", "center":"Koyritola", "city":"Jamshedpur", "state":"JH", "sponsor":"Sampath S.", "pic":"5th.jpg"},
  "6999": { "teacher":"Arunima Das", "grade":"5th", "center":"Koymara", "city":"Jamshedpur", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "7007": { "teacher":"Jayna Maheshwari", "grade":"6th", "center":"Udnabad", "city":"Jamshedpur", "state":"JH", "sponsor":"Satish V", "pic":"6th.jpg"},
  "7009": { "teacher":"Akshar Shah", "grade":"7th", "center":"Mirzaganj", "city":"Jamshedpur", "state":"JH", "sponsor":"WilliamsLea ", "pic":"7th.jpg"},
  "7022": { "teacher":"Prakash Srivastava", "grade":"5th", "center":"Shitalpur", "city":"New Delhi", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "7027": { "teacher":"Rameshbabu", "grade":"7th", "center":"Topslip", "city":"Bengaluru", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "7072": { "teacher":"Sreenila Dutta", "grade":"5th", "center":"Udnabad", "city":"Bengaluru", "state":"JH", "sponsor":"Satish V", "pic":"5th.jpg"},
  "7079": { "teacher":"Soujanya", "grade":"7th", "center":"Kishikindapalem", "city":"Santa Clara", "state":"AP", "sponsor":"Raman A.", "pic":"7th.jpg"},
  "7081": { "teacher":"Sneha", "grade":"6th", "center":"Hosadurga", "city":"Hamburg", "state":"KA", "sponsor":"Infosys BPO", "pic":""},
  "7085": { "teacher":"Sucharita Mandal", "grade":"7th", "center":"Dumdumi", "city":"24 Parganas (s)", "state":"WB", "sponsor":"Dubai Chapter", "pic":"7th.jpg"},
  "7091": { "teacher":"Rashmi Singla", "grade":"6th", "center":"Itki", "city":"San Diego", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "7105": { "teacher":"Sunanda Manjunath", "grade":"6th", "center":"Thopalakatti", "city":"Erlangen", "state":"KA", "sponsor":"Infosys BPO", "pic":"6th.jpg"},
  "7127": { "teacher":"Santhosha  Aggunda Lingamurthy", "grade":"7th", "center":"Managundi", "city":"Jena", "state":"KA", "sponsor":"L&T Infotech", "pic":""},
  "7162": { "teacher":"Ishan Sharma", "grade":"", "center":"Bengabad", "city":"New Delhi", "state":"JH", "sponsor":"", "pic":""},
  "7174": { "teacher":"Kasturi Patra", "grade":"6th", "center":"Dumdumi", "city":"New Delhi", "state":"WB", "sponsor":"Dubai Chapter", "pic":"6th.jpg"},
  "7175": { "teacher":"Deepali Pathak", "grade":"8th", "center":"Udnabad", "city":"Bikaner", "state":"JH", "sponsor":"Satish V", "pic":"8th.jpg"},
  "7195": { "teacher":"Deepa Padmanabhan", "grade":"5th", "center":"Mirzaganj", "city":"Montreal", "state":"JH", "sponsor":"WilliamsLea ", "pic":"5th.jpg"},
  "7225": { "teacher":"Baisakhi Chatterjee", "grade":"7th", "center":"Dumdumi", "city":"Secunderabad", "state":"WB", "sponsor":"Dubai Chapter", "pic":"7th.jpg"},
  "7250": { "teacher":"Subhashree", "grade":"5th", "center":"Ariyur", "city":"Chennai", "state":"TN", "sponsor":"CAMS", "pic":"5th.jpg"},
  "7352": { "teacher":"Aparna Roy", "grade":"6th", "center":"Udnabad", "city":"Dubai", "state":"JH", "sponsor":"Satish V", "pic":"6th.jpg"},
  "7375": { "teacher":"Jyothi Iyer", "grade":"8th", "center":"Sonbad", "city":"Dubai", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "7376": { "teacher":"Hari Prakash", "grade":"6th", "center":"Semmambadi", "city":"Cromwell", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "7387": { "teacher":"Sujatha", "grade":"7th", "center":"Topslip", "city":"New Delhi", "state":"TN", "sponsor":"", "pic":"7th.jpg"},
  "7389": { "teacher":"Patel", "grade":"5th", "center":"Chachgura", "city":"Folsom", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "7403": { "teacher":"Tarun Karthik", "grade":"8th", "center":"Chittela", "city":"Chennai", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "7403": { "teacher":"Meenu", "grade":"6th", "center":"Jhalakdiha", "city":"Chennai", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "7472": { "teacher":"Sudha", "grade":"7th", "center":"sulligondu", "city":"Kolkata", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "7491": { "teacher":"Chitra Phadnis", "grade":"5th", "center":"Jhalakdiha", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "7541": { "teacher":"Vijaya LAXMI KAMALAPURI", "grade":"7th", "center":"Chachgura", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "7586": { "teacher":"Bindu", "grade":"Centre Admin", "center":"Mallella", "city":"Gurgaon", "state":"AP", "sponsor":"", "pic":"5thv.jpg"},
  "7586": { "teacher":"Bindu", "grade":"Centre Admin", "center":"Mallella", "city":"Gurgaon", "state":"AP", "sponsor":"", "pic":"6thm.jpg"},
  "7586": { "teacher":"Bindu", "grade":"6th", "center":"Mallella", "city":"Gurgaon", "state":"AP", "sponsor":"", "pic":"6thm.jpg"},
  "7602": { "teacher":"Neha", "grade":"5th", "center":"Shitalpur", "city":"Thane", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "7704": { "teacher":"Oindrilla Mukherjee", "grade":"5th", "center":"Dumdumi", "city":"Kolkata", "state":"WB", "sponsor":"Dubai Chapter", "pic":"5th.jpg"},
  "7735": { "teacher":"laxmi", "grade":"6th", "center":"Vamakuntala", "city":"Hyderabad", "state":"AP", "sponsor":"Manish Kotwala", "pic":"6th.jpg"},
  "7739": { "teacher":"Vibhor", "grade":"6th", "center":"Koymara", "city":"Delft", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "7747": { "teacher":"Shuchi Joshi", "grade":"7th", "center":"Chengarbasa", "city":"Schaumburg", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"7th.jpg"},
  "7893": { "teacher":"Kameswari", "grade":"6th", "center":"Topslip", "city":"Secunderabad", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "7895": { "teacher":"Abhinav Shrivastava", "grade":"6th", "center":"Bajpur", "city":"Mumbai", "state":"JH", "sponsor":"Shankar A", "pic":"6th.jpg"},
  "7900": { "teacher":"Sharmila Roy", "grade":"6th", "center":"Dumdumi", "city":"Jakarta", "state":"WB", "sponsor":"Dubai Chapter", "pic":"6th.jpg"},
  "7940": { "teacher":"Tribhuwan", "grade":"6th", "center":"Jhalakdiha", "city":"Los Angeles", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "7952": { "teacher":"Gayathri Arunkumar", "grade":"6th", "center":"Esanaikorai", "city":"Madurai", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "8068": { "teacher":"Narmada", "grade":"7th", "center":"Konijerla", "city":"Kakinada", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "8075": { "teacher":"Kavitha", "grade":"7th", "center":"sulligondu", "city":"Richmond", "state":"TN", "sponsor":"CAMS", "pic":"7th.jpg"},
  "8100": { "teacher":"Iswarya", "grade":"5th", "center":"Ariyur", "city":"Madurai", "state":"TN", "sponsor":"CAMS", "pic":"5th.jpg"},
  "8101": { "teacher":"Janakiram Jayaraman", "grade":"5th", "center":"Hanasoge", "city":"Bengaluru", "state":"KA", "sponsor":"", "pic":"5th.jpg"},
  "8102": { "teacher":"Lokanna Hoskoti", "grade":"7th", "center":"Hanasoge", "city":"Ramdurg", "state":"KA", "sponsor":"", "pic":"7th.jpg"},
  "8116": { "teacher":"Murali ", "grade":"7th", "center":"Konijerla", "city":"Newington", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "8182": { "teacher":"Dimple Mhajan", "grade":"6th", "center":"Sonbad", "city":"Faridabad", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "8208": { "teacher":"Richa Diwan", "grade":"7th", "center":"Shitalpur", "city":"Delhi", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "8213": { "teacher":"Jyoti Gambhir", "grade":"7th", "center":"Girdih ", "city":"New Delhi", "state":"JH", "sponsor":"", "pic":""},
  "8218": { "teacher":"Mahesh Chavan", "grade":"8th", "center":"Shitalpur", "city":"Pune", "state":"JH", "sponsor":"", "pic":"8th.jpg"},
  "8221": { "teacher":"Neha Yadav", "grade":"5th", "center":"Mirzaganj", "city":"Lucknow", "state":"JH", "sponsor":"WilliamsLea ", "pic":"5th.jpg"},
  "8354": { "teacher":"Rohit wadhwa", "grade":"5th", "center":"Udnabad", "city":"Kolkata", "state":"JH", "sponsor":"Satish V", "pic":"5th.jpg"},
  "8357": { "teacher":"Arvind Akhilesh", "grade":"7th", "center":"Jhalakdiha", "city":"Amethi", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "8359": { "teacher":"Lal Bahadur", "grade":"7th", "center":"Shitalpur", "city":"Kolkata", "state":"JH", "sponsor":"", "pic":"7th.jpg"},
  "8383": { "teacher":"Mallikarjun Tirlapur", "grade":"6th", "center":"Thopalakatti", "city":"Allershausen", "state":"KA", "sponsor":"Infosys BPO", "pic":"6th.jpg"},
  "8401": { "teacher":"Chitra Raju", "grade":"6th", "center":"Semmambadi", "city":"Hyderabad", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "8402": { "teacher":"Snigdha Agarwal", "grade":"6th", "center":"Sonbad", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "8418": { "teacher":"Vani bala", "grade":"7th", "center":"Chittela", "city":"Visakhapatnam", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "8437": { "teacher":"Chaitanya Bharathi", "grade":"5th", "center":"Mallella", "city":"Nalgonda", "state":"AP", "sponsor":"", "pic":"5thv.jpg"},
  "8447": { "teacher":"Bhavisha Zaveri", "grade":"5th", "center":"Itki", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "8453": { "teacher":"Hupesh", "grade":"Admin", "center":"Chittela", "city":"Kurnool", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "8453": { "teacher":"Hupesh", "grade":"8th", "center":"Chittela", "city":"Kurnool", "state":"AP", "sponsor":"", "pic":"8th.jpg"},
  "8454": { "teacher":"Sudha mani", "grade":"5th", "center":"Mallella", "city":"Guntur", "state":"AP", "sponsor":"", "pic":"5thv.jpg"},
  "8566": { "teacher":"Archana Saraswat", "grade":"6th", "center":"Mirzaganj", "city":"Gwalior", "state":"JH", "sponsor":"WilliamsLea ", "pic":"6th.jpg"},
  "8588": { "teacher":"Ashwini Leeza", "grade":"6th", "center":"Halagondanahalli", "city":"Mysore", "state":"KA", "sponsor":"Infosys BPO", "pic":"6th.jpg"},
  "8611": { "teacher":"Shashidhar Bhat", "grade":"6th", "center":"Mugad", "city":"Delhi", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "8653": { "teacher":"Meenakshi Guhan", "grade":"6th", "center":"Topslip", "city":"Chennai", "state":"TN", "sponsor":"", "pic":"6th.jpg"},
  "8683": { "teacher":"Deepika Anvekar", "grade":"6th", "center":"Mugad", "city":"Bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "8691": { "teacher":"Jananie", "grade":"6th", "center":"Ariyur", "city":"Bengaluru", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "8716": { "teacher":"Amrita Kataruka", "grade":"5th", "center":"Itki", "city":"Champaign", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "8721": { "teacher":"Vivek Prasad", "grade":"6th", "center":"Halagondanahalli", "city":"Miami", "state":"KA", "sponsor":"Infosys BPO", "pic":"6th.jpg"},
  "8864": { "teacher":"Madhumathi", "grade":"6th", "center":"Mugad", "city":"Nagpur", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "8916": { "teacher":"Reena J", "grade":"5th", "center":"Chengarbasa", "city":"Mumbai", "state":"JH", "sponsor":"Vipul, Sreedhar", "pic":"5th.jpg"},
  "8941": { "teacher":"Sanjam Sachdeva", "grade":"6th", "center":"Bengabad", "city":"Ambala Cantt", "state":"JH", "sponsor":"", "pic":""},
  "8959": { "teacher":"Pavan Munavalli", "grade":"5th", "center":"Hanasoge", "city":"Hamburg", "state":"KA", "sponsor":"", "pic":"5th.jpg"},
  "8994": { "teacher":"Garima Jindal", "grade":"", "center":"Bengabad", "city":"Overland Park", "state":"JH", "sponsor":"", "pic":""},
  "9033": { "teacher":"Atanu Bhuyan", "grade":"6th", "center":"Bengabad", "city":"Dibrugarh", "state":"JH", "sponsor":"", "pic":""},
  "9075": { "teacher":"Sruthi", "grade":"5th", "center":"Rolupadi", "city":"Singapore", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "9118": { "teacher":"Shilpa", "grade":"6th", "center":"Shitalpur", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":"6th.jpg"},
  "9147": { "teacher":"RaviTeja", "grade":"7th", "center":"Lakshmipuram", "city":"Bhadrachalam", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "9185": { "teacher":"Aditi Banerjee ", "grade":"Admin", "center":"Dumdumi", "city":"Bengaluru", "state":"WB", "sponsor":"Dubai Chapter", "pic":""},
  "9252": { "teacher":"Niveditha", "grade":"6th", "center":"Mallella", "city":"El Paso", "state":"AP", "sponsor":"", "pic":"6thv.jpg"},
  "9269": { "teacher":"Madhavi", "grade":"5th", "center":"Gosaveedu", "city":"Chantilly", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "9315": { "teacher":"Sharanya Vaidyanath", "grade":"5th", "center":"Hosadurga", "city":"Bengaluru", "state":"KA", "sponsor":"Infosys BPO", "pic":""},
  "9316": { "teacher":"Sai Divya", "grade":"7th", "center":"Juvalepalem", "city":"Cuddapah", "state":"AP", "sponsor":"", "pic":"7th.jpg"},
  "9375": { "teacher":"Nandini", "grade":"5th", "center":"Halagondanahalli", "city":"Mumbai", "state":"KA", "sponsor":"Infosys BPO", "pic":"5th.jpg"},
  "9404": { "teacher":"Rakesh", "grade":"6th", "center":"Mugad", "city":"Hamburg", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "9438": { "teacher":"Madhavi", "grade":"6th", "center":"Mallella", "city":"Bengaluru", "state":"AP", "sponsor":"", "pic":"6thv.jpg"},
  "9485": { "teacher":"Krithika", "grade":"6th", "center":"Sathamangala", "city":"Bengaluru", "state":"TN", "sponsor":"CAMS", "pic":"6th.jpg"},
  "9596": { "teacher":"Swarna", "grade":"7th", "center":"Hanumasagara", "city":"Bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "9612": { "teacher":"Devesh Wadhwani", "grade":"7th", "center":"Bengabad", "city":"Bengaluru", "state":"JH", "sponsor":"", "pic":""},
  "9621": { "teacher":"KRITIKA RAJ", "grade":"5th", "center":"Sonbad", "city":"Karimnagar", "state":"JH", "sponsor":"", "pic":"5th.jpg"},
  "9695": { "teacher":"Vinay Puttanna", "grade":"7th", "center":"Halagondanahalli", "city":"San Jose", "state":"KA", "sponsor":"Infosys BPO", "pic":"7th.jpg"},
  "9746": { "teacher":"Alakananda", "grade":"7th", "center":"Hanumasagara", "city":"San Diego", "state":"KA", "sponsor":"L&T Infotech", "pic":"7th.jpg"},
  "9778": { "teacher":"Harika Rathode", "grade":"7th", "center":"Mallella", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"7thm.jpg"},
  "9794": { "teacher":"Pushpalatha.M", "grade":"6th", "center":"Managundi", "city":"Bengaluru", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "9825": { "teacher":"Deepika Haliyal", "grade":"6th", "center":"Managundi", "city":"Dharwar", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "9852": { "teacher":"Narendra Reddy", "grade":"6th", "center":"Hosadurga", "city":"Berlin", "state":"KA", "sponsor":"Infosys BPO", "pic":""},
  "9874": { "teacher":"Sanjay Kumar", "grade":"7th", "center":"Udnabad", "city":"New Delhi", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "9874": { "teacher":"Sanjay Gupta", "grade":"6th", "center":"Udnabad", "city":"New Delhi", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "9883": { "teacher":"Sharanmai Ghone", "grade":"5th", "center":"Rolupadi", "city":"Hyderabad", "state":"AP", "sponsor":"", "pic":"6th.jpg"},
  "9957": { "teacher":"Abhishek Chauhan", "grade":"7th", "center":"Udnabad", "city":"Lucknow", "state":"JH", "sponsor":"Satish V", "pic":"7th.jpg"},
  "9976": { "teacher":"Satan kumar bhagat", "grade":"", "center":"Girdih ", "city":"Bathinda", "state":"JH", "sponsor":"", "pic":""},
  "10030": { "teacher":"Bhumika Goel", "grade":"6th", "center":"Girdih ", "city":"Hyderabad", "state":"JH", "sponsor":"", "pic":""},
  "10038": { "teacher":"Prashant Goklani", "grade":"7th", "center":"Bero", "city":"Bengaluru", "state":"JH", "sponsor":"BGMRT", "pic":"7thhira.jpg"},
  "10048": { "teacher":"Darshinee Patel", "grade":"7th", "center":"Girdih ", "city":"Mundra", "state":"JH", "sponsor":"", "pic":""},
  "10153": { "teacher":"Abhishek Verma", "grade":"6th", "center":"Girdih ", "city":"Bareilly", "state":"JH", "sponsor":"", "pic":""},
  "10332": { "teacher":"Sunil Shetty", "grade":"5th", "center":"Lakshmipuram", "city":"San Jose", "state":"AP", "sponsor":"", "pic":"5th.jpg"},
  "10401": { "teacher":"Shabareesha KP", "grade":"6th", "center":"Benakanakatti", "city":"Visakhapatnam", "state":"KA", "sponsor":"L&T Infotech", "pic":"6th.jpg"},
  "10448": { "teacher":"Vilasani", "grade":"6th", "center":"Kishikindapalem", "city":"Karimnagar", "state":"AP", "sponsor":"Raman A.", "pic":"6th.jpg"}
}
